# Generated by Django 5.0.6 on 2024-06-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='receipe',
            name='receipe_ingredient',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipe',
            name='receipe_process',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
